<div class="footer footer-light statements statements-common text-center text-md-left">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md">
                <h3><a href="features.html">Features</a></h3>
                <h3><a>Solutions</a></h3>
                <a href="solutions-live.html">Live Streaming</a>
                <a href="solutions-learning.html">E-learning</a>
                <a href="solutions-video.html">Webinars</a>
            </div>
            <div class="col-12 col-md">
                <h3><a href="#">Alternatives</a></h3>
                <a href="#">TokBox alternative</a>
                <a href="#">Twilio alternative</a>
                <a href="#">Liveswitch alternative</a>
            </div>
            <div class="col-12 col-md">
                <h3><a href="pricing.html">Pricing</a></h3>
                <h3><a href="development.html">WebRTC Development</a></h3>
                <h3><a href="about.html">About</a></h3>
            </div>
            <div class="col-12 col-md d-none d-lg-block">

            </div>
            <div class="col-12 col-md mt-5 mt-md-0">
                <h3>Contact</h3>
                <p class="font-weight-bold">Codedo LP</p>
                <p>Office 29, Clifton House, Fitzwilliam Street Lower Dublin 2, D02 XT91</p>
                <p>REPUBLIC OF IRELAND</p>
                <p><a href="mailto:anovikov@avcore.io">anovikov@avcore.io</a></p>
                <p>United States <a href="tel:+12016441996">+12016441996</a></p>
				<p>Ireland <a href="tel:+35319609548">+35319609548</a></p>
                <p>Czech Republic <a href="tel:+420775984038">+420775984038</a></p></p>

            </div>
        </div>
    </div>
</div>

<div class="footer footer-dark">
    <div class="container align-self-center">
        <div class="row">
            <div class="col">Copyright ©</div>
            <div class="col text-right"><a href="#">Terms</a> and <a href="privacy.html">Privacy</a></div>
        </div>
    </div>
</div>

<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/5f96ba642915ea4ba096b9f1/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->