<link rel="preload" href="fonts/Metropolis-Regular.woff2" as="font" />
<link rel="preload" href="fonts/Metropolis-Bold.woff2" as="font" />
<link rel="preload" href="fonts/SofiaProRegular.woff2" as="font" />
<link rel="preload" href="fonts/SofiaProLight.woff2" as="font" />
<link rel="preload" href="fonts/SofiaProMedium.woff2" as="font" />
<link rel="preload" href="fonts/SofiaProSemiBold.woff2" as="font" />