<div class="bg-grey noselect border-top-grey navbar-secondary-wrapper">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-secondary">

            <div>
                <h2 class="d-none d-lg-block">Home</h2>
                <h1><%=title%></h1>
            </div>

            <button class="navbar-toggler navbar-toggler-right toggler-any ml-auto" type="button" data-toggle="collapse"
                    data-target="#sub-menu">
        <span class="navbar-toggler-icon">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-down" fill="currentColor"
                 xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd"
        d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
</svg>
        </span>
            </button>

            <div class="navbar-sub collapse navbar-collapse" id="sub-menu">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="solutions-live.html">Live Streaming</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="solutions-video.html">Video Conferencing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="solutions-learning.html">E-learning</a>
                    </li>
                </ul>
            </div>

        </nav>
    </div>
</div>

